### ISSUE TITLE
`with_output_limit` undefined

### ISSUE THREAD

**Issue by staticfloat** [JuliaCI/Coverage.jl#100]
This seems to have broken on `v0.5` since about December 30th.  See [this log](https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/19/steps/Gather%20test%20results%20and%20Submit/logs/stdio) for details:

```
ERROR: UndefVarError: with_output_limit not defined
 in dump at show.jl:1032
 in submit_token at /home/ubuntu/.julia/v0.5/Coverage/src/coveralls.jl:123
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:222
 in _start at ./client.jl:301
```

**Comment by tkelman** [comment]
I think a deprecation was added back into base to make this a warning, but we haven't had new nightlies since that fix.

**Comment by fingolfin** [comment]
I believe this issue is obsolete and can be closed: the offending call to `dump` at the end of `Coveralls.submit_token` was replaced in commit e5f0f02196257560c1f5e9dd54e22456bcc9c7e5
