### ISSUE TITLE
Coverage parse error in anonymous at /home/travis/.julia/v0.4/Coverage/src/Coverage.jl:149

### ISSUE THREAD

**Issue by tawheeler** [JuliaCI/Coverage.jl#107]
One of my code repos recently stopped submitting reports to Coveralls. I checked out the Travis build, and after passing tests it skips all of the files, assumes they have no coverage, and then fails with a ParseError:

```
ERROR: ParseError("unexpected end")
 in __parse#26__ at ./parse.jl:180
 in parse at markdown/Julia/interp.jl:5
 in anonymous at /home/travis/.julia/v0.4/Coverage/src/Coverage.jl:149
 in open at iostream.jl:114
 in amend_coverage_from_src! at /home/travis/.julia/v0.4/Coverage/src/Coverage.jl:145
 in process_file at /home/travis/.julia/v0.4/Coverage/src/Coverage.jl:182
 in process_folder at /home/travis/.julia/v0.4/Coverage/src/Coverage.jl:204
 in process_folder at /home/travis/.julia/v0.4/Coverage/src/Coverage.jl:210
 in process_folder at /home/travis/.julia/v0.4/Coverage/src/Coverage.jl:196
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
```

I could very well be screwing up something on my end. Any chance you know what the cause is?

My Travis build is [here](https://travis-ci.org/tawheeler/AutomotiveDrivingModels.jl).

**Comment by tawheeler** [comment]
Ended up being a src file that is not ever pulled in by the module (ie, cruft) that consisted entirely of commented out lines and a single uncommented `end' at the end.

**Comment by tkelman** [comment]
Hah, glad you got to the bottom of it. So Coverage.jl is running on all the files in your package whether or not they get used?
