### ISSUE TITLE
Tag a new release for appveyor support.

### ISSUE THREAD

**Issue by rofinn** [JuliaCI/Coverage.jl#130]
Low priority, but I'm getting this error on appveyor.
```
ERROR: KeyError: key "TRAVIS_BRANCH" not found
 in access_env(::Base.##351#352, ::String) at .\env.jl:14
 in #submit#4(::Array{Any,1}, ::Function, ::Array{Coverage.FileCoverage,1}) at C:\Users\appveyor\.julia\v0.5\Coverage\src\codecovio.jl:68
 in submit(::Array{Coverage.FileCoverage,1}) at C:\Users\appveyor\.julia\v0.5\Coverage\src\codecovio.jl:68
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
Command exited with code 1
```
Any idea why it would think it was on travis?

The appveyor file is https://github.com/invenia/Keras.jl/blob/master/appveyor.yml.

**Comment by tkelman** [comment]
master or release of Coverage.jl? guess we haven't tagged since https://github.com/JuliaCI/Coverage.jl/pull/126 was merged

**Comment by rofinn** [comment]
Yeah, it would be using a release of Coverage.jl

**Comment by rofinn** [comment]
Thank you!

**Comment by tkelman** [comment]
No problem, thanks to you and your colleagues for caring more about coverage than I do.

You don't need appveyor coverage on julia 0.4, do you? We haven't technically dropped 0.4 support on master here yet but to be on the safe side I made that release 0.5-only in metadata for now.

**Comment by rofinn** [comment]
No, I think we've mostly dropped 0.4 support on our end.
