### ISSUE TITLE
Exclude `@static` lines from required coverage count

### ISSUE THREAD

**Issue by kmsquire** [JuliaCI/Coverage.jl#139]
Relevant location: https://coveralls.io/builds/14165929/source?filename=src%2Faccumulator.jl#L29

(I realize that this package isn't really maintained well right now, but in case I get some time or someone has an itch to scratch...)

**Comment by tkelman** [comment]
Might be better to collect coverage data from multiple separate runs and aggregate them? Assuming this is usually a platform or version-of-julia thing.

**Comment by kmsquire** [comment]
For some reason, I can’t see the file in the link above, but it seems that coverage data is already aggregated across multiple runs. It’s the `@static if VERSION < ...` line itself which has no coverage, which is obviously wrong.

**Comment by fingolfin** [comment]
@kmsquire the link you gave is broken. (I'd recommend in general to always write self-contained issue descriptions, and only use links to provide additional information or examples). 

As it is, the suggestion to collect and merge code coverage for different build runs and configurations seems plausible to me. Are you sure this does not work? Of course if none of the builds hits the particular condition of the `@static`, that won't help -- but then I'd argue the code in the `@static` is rightfully shown as not covered.
