### ISSUE TITLE
Coverage submission broken: undefined symbol: mbedtls_x509_crt_verify_restartable 

### ISSUE THREAD

**Issue by tkoolen** [JuliaCI/Coverage.jl#198]
See https://github.com/JuliaWeb/MbedTLS.jl/issues/193 for more info.

**Comment by fingolfin** [comment]
Note sure if we can or should do something about this in Coverage.jl? To me, it sounds like an issues that needs to be resolved in MbedTLS.jl. But perhaps we can workaround it somehow for project using Coverage.jl? If so, a PR would be highly welcome!

**Comment by fingolfin** [comment]
This has been fixed now, yay!
