### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by davidanthoff** [JuliaCI/Coverage.jl#207]
@fingolfin Could you tag a release? Would be good to get the recent fixes out into the ecosystem, and we have a project that is waiting for this with some urgency :)

**Comment by ararslan** [comment]
Max, all that's required is to make a release using the GitHub web UI. We have [Attobot](https://github.com/attobot/attobot) installed organization-wide here, and that takes care of the remainder of the release steps.

**Comment by fingolfin** [comment]
I'll take care of it once PR #208 is ready and merged.

**Comment by fingolfin** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/22006

**Comment by ararslan** [comment]
Thanks for taking care of this!
