### ISSUE TITLE
Support for GitLab CI?

### ISSUE THREAD

**Issue by vlandau** [JuliaCI/Coverage.jl#226]
I'm currently developing a Julia package using Gitlab and I'm hoping to use the built in CI (GitLab CI). I've got an example repo [here](https://gitlab.com/vlandau/GitlabJuliaDemo.jl/), and when I run the pipeline I get this error:
```
ERROR: No compatible CI platform detected
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] #add_ci_to_kwargs#3(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function) at /root/.julia/packages/Coverage/c1tw7/src/codecovio.jl:130
 [3] add_ci_to_kwargs at /root/.julia/packages/Coverage/c1tw7/src/codecovio.jl:73 [inlined]
 [4] #submit#2(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Array{FileCoverage,1}) at /root/.julia/packages/Coverage/c1tw7/src/codecovio.jl:68
 [5] submit(::Array{FileCoverage,1}) at /root/.julia/packages/Coverage/c1tw7/src/codecovio.jl:68
 [6] top-level scope at none:0
```

I'm guessing this is because I'm using GitLab's CI, but I may have an error in my yml. Is Coverage.jl only compatible with Travis and AppVeyor?

Thanks for any guidance.

**Comment by vlandau** [comment]
From [this code](https://github.com/JuliaCI/Coverage.jl/blob/master/src/coveralls.jl#L70-L97), I see that GitLab CI must not be supported. Is it a reasonable feature request to get that support for GitLab CI added?

**Comment by ararslan** [comment]
It's possible to use this package to collect/prepare the coverage data, but you'll have to do the submission step manually, since that's the part that isn't supported in this package for GitLab. Perhaps @omus could provide some guidance here, being an expert on GitLab?

**Comment by vlandau** [comment]
Thanks @ararslan. I'm had also wondered if it might instead be possible to submit the results "locally" from within the CI container via `julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'`, since this would also achieve the goal of having everything integrated, but when trying that, I got this error:
```
HTTP.ExceptionRequest.StatusError(400, "POST", "/upload/v2?&commit=be3fbdb438b19a908318121d3c9815b741cda071&branch=HEAD&token=\"<TOKEN>\""
```
(I replaced the actual CODECOV token in that line with <TOKEN>)

This error may actually have nothing to do with Coverage.jl, but figured I would include it for completeness.

**Comment by vlandau** [comment]
Eureka! I got it working using `julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'` as above in the .gitlab-ci.yml

The error I was reporting above was actually due to putting the CODECOV_TOKEN environment variable in quotes... whoops. I removed the quotes and all is working now!

**Comment by ararslan** [comment]
Fantastic!

**Comment by tpapp** [comment]
Thanks for coming up with this. I will add it to https://gitlab.com/tkpapp/GitlabJuliaDemo.jl
