### ISSUE TITLE
.codecov.yml not detected

### ISSUE THREAD

**Issue by holgerteichgraeber** [JuliaCI/Coverage.jl#229]
I am trying to ignore a folder in my repository from coverage.

The .codecov.yml I have added to the root of my project (https://github.com/holgerteichgraeber/ClustForOpt.jl/tree/testing )  seems not to be recognized, codecov.io still counts the folder that I want to be ignored. 
Any thoughts on this are appreciated, thank you.

https://codecov.io/gh/holgerteichgraeber/ClustForOpt.jl/tree/testing/src/clustering/shape_based

**Comment by fingolfin** [comment]
Sounds like a bug in codecov (I have had the exact same issue before). You'll need to raise that with their support, I guesd

**Comment by DilumAluthge** [comment]
For what it's worth, the only way that I have been able to get CodeCov to recognize my configuration file is to name it `codecov.yml` (i.e. no leading dot).

When I name it `codecov.yml`, CodeCov seems to recognize it without any problems.

Can you try renaming your file from `.codecov.yml` to `codecov.yml` and see if that works?

**Comment by fingolfin** [comment]
Thousands of projects use .codecov.yml; whatever it was that fixed your project, I doubt it was the filename.

But codecov is indeed having issues recently. Eg currently, PR comments by Codecov sometimes take several days (!) to arrive for us.

**Comment by fingolfin** [comment]
Anyway, this is not an issue caused by or fixable by Coverage.jl. Please contact the Codecov support instead.
