### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by davidanthoff** [JuliaCI/Coverage.jl#235]
Could someone please tag a release? We now have a `master` version that supports new CI platforms, and tagging a new release here is blocking deployment of that right now.

**Comment by davidanthoff** [comment]
Bump, can someone please tag a release?

Not clear to me who is in charge of this repo, so I'm going to tag some random folks that have worked on it lately and seem to have the necessary rights here to tag: @fingolfin, @ararslan, @vtjnash.

Thanks :)

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/3822

**Comment by davidanthoff** [comment]
Thanks, much appreciated!
