### ISSUE TITLE
Add instructions for coverage reporting using Pkg.test

### ISSUE THREAD

**Issue by marekdedic** [JuliaCI/Coverage.jl#236]
Hi,
the current instructions in the readme say that you should run `julia --code-coverage=user`. While in some cases, this might be applicable, in the case of using `Pkg.test()`, this will not work - the coverage won't get reported. You need to use something like `julia --project -e "using Pkg; Pkg.test(; coverage = true);"`

I don't know whether to replace the instructions or just add this somehow. However, this way of turning coverage on is actually **preferable** - if you are using the Julia 1.2.0 test-only dependencies, the only way to invoke tests (AFAIK) is to use `Pkg.test()` - using `include("test/runtests.jl")` will not work.

**Comment by marekdedic** [comment]
Related to #9

**Comment by DilumAluthge** [comment]
I think that these instructions are already in the README, right?

For example, if you look at item 2 under https://github.com/JuliaCI/Coverage.jl/blob/master/README.md#tracking-coverage-with-codecovio, it says:
> 2. Use the command line option when you run your tests:
> - Either with something like `julia --code-coverage test/runtests.jl`, or
> - with something like `julia -e 'Pkg.test("MyPkg", coverage=true)'`

**Comment by marekdedic** [comment]
Ugh, I missed it down there...

I was talking about the instructions at the top of the readme...

Thanks,
Marek

**Comment by DilumAluthge** [comment]
@marekdedic Does this seem better? https://github.com/JuliaCI/Coverage.jl/pull/248

**Comment by marekdedic** [comment]
Definitely, thanks!
