### ISSUE TITLE
Install Julia Registrator on this repo?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/Coverage.jl#259]
Could an admin please install the Julia Registrator GitHub app on this repository?

**Comment by ararslan** [comment]
It's already enabled for all repos in this org

**Comment by DilumAluthge** [comment]
For several hours earlier today, the Registrator GitHub app did not respond to me at all :(

This happened across multiple orgs.

Anyway, it is responding again now, so I guess it was an intermittent failure. While it was down, I was still able to use the web UI.
