### ISSUE TITLE
Coverage.jl reporting lines surrounded by covered code as not covered

### ISSUE THREAD

**Issue by vlandau** [JuliaCI/Coverage.jl#261]
I'm noticing issues with a coverage report for my Julia package submitted to codecov showing lines of code as not covered that are surrounded by covered code. There is no control flow in this section of code -- basically, if lines n and n+2 were covered, then line n+1 must have also been covered, but the report is stating otherwise.

It could be something on codecov's end also, but wanted to post this here to make devs aware.
Here is [the coverage report](https://codecov.io/gh/Circuitscape/Omniscape.jl/src/c58b3e279041a34a9b23b233365cf01789ac462d/src/functions.jl#L219...239) with an example highlighted for reference.

**Comment by baggepinnen** [comment]
Was the line counted at all? Maybe that line was elided by the compiler in case it counts as neither a hit or a miss. That usually applieds to constant definitions etc.

**Comment by DilumAluthge** [comment]
@vlandau Can you try running your test suite with inlining disabled, and see if that fixes the problem? I opened a pull request here: https://github.com/Circuitscape/Omniscape.jl/pull/14

**Comment by vlandau** [comment]
Thanks @DilumAluthge! Trying it now.

**Comment by vlandau** [comment]
It does seem that the coverage errors were significantly worse when the `after_script` in travis was run after the documentation stage. I added some control for to the `after_script` to only have it run after the Test stage on Linux, and the problem was reduced significantly. There is still one case, [here](https://codecov.io/gh/Circuitscape/Omniscape.jl/src/6c50df65fedac04780b8ec66b41df597ca30a607/src/run_omniscape.jl#L102...104).

Note that this is all before trying with no inlining. I'll post the results here once that finishes running.

**Comment by vlandau** [comment]
The previous comment above seems to still apply. There are two cases with skipped lines: [here](https://codecov.io/gh/Circuitscape/Omniscape.jl/src/69da613ade300b297ca7cd2299d78c56bf4a9b68/src/run_omniscape.jl#L102...104), and [here](https://codecov.io/gh/Circuitscape/Omniscape.jl/src/69da613ade300b297ca7cd2299d78c56bf4a9b68/src/run_omniscape.jl#L167...171). I can live with this just fine for now, but a fix probably does exist.

**Comment by DilumAluthge** [comment]
In the second case (line 168 of `run_omniscape.jl`), are you sure that the line is being run?

**Comment by vtjnash** [comment]
Expected to be fixed by https://github.com/JuliaLang/julia/pull/34254

**Comment by vlandau** [comment]
> In the second case (line 168 of `run_omniscape.jl`), are you sure that the line is being run?

:man_facepalming: I thought I had a test that covered that line but I actually did not! Whoops.

**Comment by vlandau** [comment]
Appears to have been fixed (presumably by [JuliaLang/julia#34254](https://github.com/JuliaLang/julia/pull/34254)). Line count is still not perfect (some lines are skipped), but there are no longer any false negatives in the report (e.g. lines that were covered that are being reported as not covered). Closing this since it was about those false negatives.
