### ISSUE TITLE
Readme instructions unclear

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCI/Coverage.jl#262]
In the readme on step 3 of running the tests with codecov.io, it says to set "codecov: true". 

However, in the example linked at the bottom of the readme, none of the repos seem to do that. Is it outdated or just optional? If it's optional, what does it actually do?

**Comment by vtjnash** [comment]
some of them do that, e.g. https://github.com/JuliaData/YAML.jl/blob/master/.travis.yml
