### ISSUE TITLE
Bug: Function declaration shown as missed although function body is hit

### ISSUE THREAD

**Issue by briochemc** [JuliaCI/Coverage.jl#277]
So I have codecov setup on [AIBECS.jl](https://github.com/JuliaOcean/AIBECS.jl) and it oddly shows the lines declaring functions as missed. Here is a screenshot of such a case:

<img width="845" alt="Screen Shot 2020-08-12 at 12 08 29 am" src="https://user-images.githubusercontent.com/4486578/89961983-bcd49c00-dc86-11ea-9c4f-322b67400672.png">

and [here](https://codecov.io/gh/JuliaOcean/AIBECS.jl/src/master/src/Archer_etal_2000.jl#L34) is a link to a similar codecov report with the same bug. 

@vtjnash mentioned on slack that it may be due to a recent change in how line coverage was stored, and suggested I file a bug report, so here it is!

**Comment by DilumAluthge** [comment]
@vtjnash ^

**Comment by briochemc** [comment]
Bump in case this got forgotten with GitHub's notification system? 

Also saw that this bug is produced for the coverage of... Coverage.jl! See, e.g., https://codecov.io/gh/JuliaCI/Coverage.jl/src/master/src/codecovio.jl#L36

**Comment by fingolfin** [comment]
@vtjnash ping?

**Comment by vtjnash** [comment]
Those linked reports all look correct to me

**Comment by briochemc** [comment]
The line declaring the function looks green *now*, but still shows less hits than the function body, which cannot be correct, right?

**Comment by fingolfin** [comment]
https://codecov.io/gh/JuliaCI/Coverage.jl/src/master/src/codecovio.jl looks fine right now: those `function FOO(...)` lines should not be marked as code at all.

@briochemc do you have a current example that can be viewed in public?

**Comment by briochemc** [comment]
This changed again since my last message, the "declaring" lines `function FOO(...)` were marked as code 4 days ago... For the record, this is what I see today when I click on https://codecov.io/gh/JuliaCI/Coverage.jl/src/master/src/codecovio.jl#L36:

<img width="646" alt="Screen Shot 2020-11-17 at 12 38 54 pm" src="https://user-images.githubusercontent.com/4486578/99329230-e29abe00-28d1-11eb-952e-f8ed45183c75.png">

So yes, this looks fine now! 😃 If the Coverage.jl example is fine then I guess the issue has been resolved? 

> @briochemc do you have a current example that can be viewed in public?

I'm not sure I understand what you mean? Both Coverage.jl and AIBECS.jl are public repositories and their coverages can be viewed "publicly", no?

**Comment by vtjnash** [comment]
> The line declaring the function looks green now, but still shows less hits than the function body, which cannot be correct, right?

It's merging reports from multiple Julia versions, so that is correct.

It's public, but Github might be blocking codecovio from displaying the source code for unauthenticated users, which may be resulting in confusion when not logged in to codecovio also (https://community.codecov.io/t/github-api-forbidden/1295/5)
