### ISSUE TITLE
better github action support?

### ISSUE THREAD

**Issue by kyungminlee** [JuliaCI/Coverage.jl#284]
`add_ci_to_kwargs` from `codecovio.jl` can be updated to provide better support for GitHub Action. Current version ignores branch when submitting to CodeCov.

https://github.com/JuliaCI/Coverage.jl/blob/9ddfeafdbc5e8bf883967781d3d64460aadfa245/src/codecovio.jl#L142-L147

**Comment by fingolfin** [comment]
Unfortunately nobody is really working on Coverage.jl right now. If you have an inkling of what needs to be done here (e.g. how to figure out the correct branch and how to submit it), perhaps consider submitting a PR to Coverage.jl to get it done?
