### ISSUE TITLE
Add GitHub Actions based CI for this repository

### ISSUE THREAD

**Issue by fingolfin** [JuliaCI/Coverage.jl#292]

**Comment by DilumAluthge** [comment]
This is done now: https://github.com/JuliaCI/Coverage.jl/blob/master/.github/workflows/CI.yml (e.g. https://github.com/JuliaCI/Coverage.jl/blob/c0abb4bd9ffc5ebddf9856011aa2fd8957a190bd/.github/workflows/CI.yml)
