### ISSUE TITLE
Hi @usandourkids525. This comment does not seem to be relevant to this repository, so I'm going to close the issue. Please feel free to open a new issue if you find you're having issues using Coverage.jl for collecting/submitting code coverage information for Julia code.how would it be more relevant to the issue

### ISSUE THREAD

**Issue by usandourkids525** [JuliaCI/Coverage.jl#303]
Hi @usandourkids525. This comment does not seem to be relevant to this repository, so I'm going to close the issue. Please feel free to open a new issue if you find you're having issues using Coverage.jl for collecting/submitting code coverage information for Julia code.

__Originally posted by @ararslan in https://github.com/JuliaCI/Coverage.jl/issues/302#issuecomment-778332594__

**Comment by timholy** [comment]
@usandourkids525, please desist unless you have something constructive to contribute.
