### ISSUE TITLE
local declaration not counting as covered

### ISSUE THREAD

**Issue by fchorney** [JuliaCI/Coverage.jl#322]
I don't currently have a MWE but I found this to be quite curious. It seems that coverage doesn't count this declaration of local variables as covered.

![image](https://user-images.githubusercontent.com/202139/122957257-61b01300-d347-11eb-9a8d-ac57e4bdf777.png)

Is there any other info that I might be able to give you that would help resolve this?

**Comment by fchorney** [comment]
oops I need to put this in julia rather than here. Sorry!

**Comment by vtjnash** [comment]
I think there is one already, but I'm trying to find it for xref

**Comment by fchorney** [comment]
yes I did find it https://github.com/JuliaLang/julia/issues/39307
