### ISSUE TITLE
Issue with appveyor

### ISSUE THREAD

**Issue by CNelias** [JuliaCI/Coverage.jl#328]
I included the recommended line
```
after_test:
- C:\projects\julia\bin\julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(process_folder())"
```
in my [appveyor.yml](https://github.com/johncwok/CategoricalTimeSeries.jl/blob/main/appveyor.yml) file, which is not recognized correctly by appveyor and returns the following error:
```Julia
C:\projects\julia\bin\julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(process_folder())"
The system cannot find the path specified.
Command exited with code 1
```
Did I miss an important detail somehow?

**Comment by vtjnash** [comment]
It looks the path to Julia changed in the AppVeyor script. Can you submit a PR to fix the README to the current path?

**Comment by johncwok** [comment]
I would, but I actually don't know the current path. I tried the following, where I thought julia to be in appveyor, but got an error.
```
C:\Users\appveyor\.julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(process_folder())"
'C:\Users\appveyor\.julia' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

**Comment by pranavvatsa** [comment]
Hey i have updated the README file to the new path. Please do verify my PR. Thanks!
