### ISSUE TITLE
clean_folder for .mem files

### ISSUE THREAD

**Issue by bluesmoon** [JuliaCI/Coverage.jl#341]
Can we get an equivalent of `clean_folder` and `clean_file` for `.mem` files as well?

**Comment by vtjnash** [comment]
PRs welcome. Note that you can also use `--code-coverage=tracefile-%p.info` to prevent the files from being created.

**Comment by bluesmoon** [comment]
I want the files to be created since I need to analyze them later. I just want to clean pre-existing files before I start.  I think it needs to go into `CoverageTools` though.

**Comment by vtjnash** [comment]
It still generates the information for analysis, it just puts it in a local file instead of scattered everywhere

**Comment by bluesmoon** [comment]
thanks. I'll look into it then.  In the meanwhile, I opened this: https://github.com/JuliaCI/CoverageTools.jl/pull/72

**Comment by bluesmoon** [comment]
Hi, can I get some help on https://github.com/JuliaCI/CoverageTools.jl/pull/72 please? I don't know what I need to do here.

**Comment by fingolfin** [comment]
Since https://github.com/JuliaCI/CoverageTools.jl/pull/72 was merged and released I assume we can close this issue now, @bluesmoon ?
