### ISSUE TITLE
Badge information not automatically filled

### ISSUE THREAD

**Issue by andreasvarga** [JuliaCI/Coverage.jl#344]
I am using the following setting in the `Readme` to show coverage information for my package [PeriodicMatrixEquations](https://github.com/andreasvarga/PeriodicMatrixEquations.jl)

`[![codecov.io](https://codecov.io/gh/andreasvarga/PeriodicMatrixEquations.jl/coverage.svg?branch=master)](https://codecov.io/gh/andreasvarga/PeriodicMatrixEquations.jl?branch=master)`

but the coverage information is not displayed. After clicking on the badge and selecting the branch` master`, I can inspect the desired information. For all other of my packages, this information is always shown. So, I am afraid something is wrong with my repository settings. 

Sorry if this is not the right place for such an issue.

**Comment by omus** [comment]
As you have coverage information being reported on https://app.codecov.io/gh/andreasvarga/PeriodicMatrixEquations.jl/tree/master the issue is most likely with your Codecov configuration. You may want to take a look at your configuration on the Codecov.io website.

**Comment by andreasvarga** [comment]
Solved.
