### ISSUE TITLE
Have an option to mark lines as "ok that this isn't covered"

### ISSUE THREAD

**Issue by davidanthoff** [JuliaCI/Coverage.jl#53]
I have a situation where I'm calling an external function that returns an int. I know all the values that this external function can return, but I want to make sure my code breaks in case the external function adds another, new return type. So my code looks like this:

```
ret = somef()
if ret==1
  # do something
elseif ret==2
  # do something
else
  error("This cannot happen with the current version of somef, but might in the future")
end
```

It would be great if there as a way to mark that line in the else block as "all good that this is not covered", so that it doesn't show up as a red line in the coverage UI.

**Comment by vtjnash** [comment]
Closed by https://github.com/JuliaCI/CoverageTools.jl/pull/35
