### ISSUE TITLE
Anonymous function as default argument in function call shows up as not covered

### ISSUE THREAD

**Issue by BenLauwens** [JuliaCI/Coverage.jl#84]
Hi

The following function call (from SimJulia) shows up in coverage as not covered but it is called several times both with and without a specific "filter" function:

function Get{T}(sto::Store{T}, filter::Function=(item::T)->true, priority::Int64=0)

The code in this function is covered without any problem.

References: 
- https://codecov.io/github/BenLauwens/SimJulia.jl/src/resources/stores.jl?ref=2153535b95dffb43c424923d471572a34e88bda1
- https://coveralls.io/builds/3386859/source?filename=src%2Fresources%2Fstores.jl

**Comment by IainNZ** [comment]
@BenLauwens can you check that the `.cov` file produced by Julia doesn't show this as covered? If so, that is a problem with Julia itself and you should file an issue there. If it does show up, then the problem could be in Coverage.jl.

**Comment by IainNZ** [comment]
Oh wait hold on, I guess that is Coverage.jl's fault, because that line shouldn't have `null` coverage, not 0... @kshyatt @timholy parser related?

**Comment by fingolfin** [comment]
It seems the issue is no longer present in https://coveralls.io/builds/19030092/source?filename=src/resources/stores.jl so I guess this can be closed?
